<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_Employee Full NameNicknameEmployee IdO_768ca4</name>
   <tag></tag>
   <elementGuidId>bbd1caf3-d842-4abf-8328-31192bb18009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]/div/form</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>form.oxd-form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>a23a0d2f-5db6-4625-90cb-76f31f669987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-form</value>
      <webElementGuid>3a1e232e-8602-44dc-bc6f-001f0cb5f034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee Full NameNicknameEmployee IdOther IdDriver's License NumberLicense Expiry DateSSN NumberSIN NumberNationality-- Select --Marital Status-- Select --Date of BirthDecember2022SMTWTFS12345678910111213141516171819202122232425262728293031TodayClearCloseGenderMaleFemaleMilitary ServiceSmokerYes * Required Save </value>
      <webElementGuid>982fa47b-e19b-47cd-acae-7aa49c1d92f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/div[@class=&quot;orangehrm-edit-employee&quot;]/div[@class=&quot;orangehrm-edit-employee-content&quot;]/div[@class=&quot;orangehrm-horizontal-padding orangehrm-vertical-padding&quot;]/form[@class=&quot;oxd-form&quot;]</value>
      <webElementGuid>ecc6f0d7-3d49-4477-945b-e319925e2d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]/div/form</value>
      <webElementGuid>4252841d-ff63-463f-91ab-1f8433cc32f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memberships'])[1]/following::form[1]</value>
      <webElementGuid>babdd568-e3de-4fe9-85d9-9e3ccd4a923c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form</value>
      <webElementGuid>d0ba7768-8769-45d5-aec6-9c9f347fca3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//form[(text() = concat(&quot;Employee Full NameNicknameEmployee IdOther IdDriver&quot; , &quot;'&quot; , &quot;s License NumberLicense Expiry DateSSN NumberSIN NumberNationality-- Select --Marital Status-- Select --Date of BirthDecember2022SMTWTFS12345678910111213141516171819202122232425262728293031TodayClearCloseGenderMaleFemaleMilitary ServiceSmokerYes * Required Save &quot;) or . = concat(&quot;Employee Full NameNicknameEmployee IdOther IdDriver&quot; , &quot;'&quot; , &quot;s License NumberLicense Expiry DateSSN NumberSIN NumberNationality-- Select --Marital Status-- Select --Date of BirthDecember2022SMTWTFS12345678910111213141516171819202122232425262728293031TodayClearCloseGenderMaleFemaleMilitary ServiceSmokerYes * Required Save &quot;))]</value>
      <webElementGuid>5fb2cd05-0c56-49ec-bbe7-c566f181369c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
